apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: registry.us-east-1.aliyuncs.com/sll0/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        volumeMounts:
        - name: guestbook
          mountPath: "/etc/guestbook.yaml"
    volumes:
    - name: guestbook
      configMap:
      name: guestbook    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook
data:
  application.yaml: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
